# Import Package and Data

In [3799]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from geopy.geocoders import ArcGIS 
import os

In [3800]:
 df = pd.read_excel('C:/Users/mbiringanine/Desktop/Week 3 Queen Foods Resequenced TS (Correct)_New.xlsx')
    
    


# Your file path 

# Extract the filename from the file path 
week = 'Week 3'

# Extract the desired portion and replace '-' with '/'

In [3801]:
pd.set_option('display.max_columns', None)
df.head()

,ID 2,Unnamed: 1,# Trip stops,Unnamed: 3,# Orders,Unnamed: 5,Motor vehicle ID,Assignment,Unnamed: 8,Trailer ID,Unnamed: 10,Vehicle type,Unnamed: 12,Weight,Unnamed: 14,% Weight,Linear feet,Unnamed: 17,Volume,Unnamed: 19,Start time,Unnamed: 21,End time,Unnamed: 23,Length,Duration,Unnamed: 26,Costs,Driving time,Unnamed: 29,Handling time,Unnamed: 31,Break time,Unnamed: 33,Rest period,Unnamed: 35,Waiting time,Restriction violations,Unnamed: 38,Unnamed: 39,Qualifications,PTrip,Unnamed: 42,Planning status,Reply status,Export status,Unnamed: 46,Data status,Unnamed: 48,Motor vehicle license number,Unnamed: 50,Unnamed: 51,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616.0,NaN,11.0,NaN,9.0,NaN,Queen (3),1.0,NaN,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaN,NaN,2385.0,NaN,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,NaN,No,NaN,Arrival,NaN,Site name,NaN,NaN,Departure,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,Start of time slot,NaN,NaN,End of time slot,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,NaN,NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,NaN,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,NaN,NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,NaN,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,NaN,NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,NaN,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Inspect Data

In [3802]:
df.shape

(900, 61)

In [3803]:
df.index

RangeIndex(start=0, stop=900, step=1)

In [3804]:
df.columns

Index(['ID 2', 'Unnamed: 1', '# Trip stops', 'Unnamed: 3', '# Orders',
       'Unnamed: 5', 'Motor vehicle ID', 'Assignment', 'Unnamed: 8',
       'Trailer ID', 'Unnamed: 10', 'Vehicle type', 'Unnamed: 12', 'Weight',
       'Unnamed: 14', '% Weight', 'Linear feet', 'Unnamed: 17', 'Volume',
       'Unnamed: 19', 'Start time', 'Unnamed: 21', 'End time', 'Unnamed: 23',
       'Length', 'Duration', 'Unnamed: 26', 'Costs', 'Driving time',
       'Unnamed: 29', 'Handling time', 'Unnamed: 31', 'Break time',
       'Unnamed: 33', 'Rest period', 'Unnamed: 35', 'Waiting time',
       'Restriction violations', 'Unnamed: 38', 'Unnamed: 39',
       'Qualifications', 'PTrip', 'Unnamed: 42', 'Planning status',
       'Reply status', 'Export status', 'Unnamed: 46', 'Data status',
       'Unnamed: 48', 'Motor vehicle license number', 'Unnamed: 50',
       'Unnamed: 51', 'Trailer license number', 'Shift potential',
       'Pretrip length', 'Pretrip duration', 'Post-trip length',
       'Post-trip duration', 'Total weight', 'Total linear feet',
       'Total volume'],
      dtype='object')

In [3805]:
df.dtypes

ID 2                  float64
Unnamed: 1             object
# Trip stops          float64
Unnamed: 3             object
# Orders              float64
                       ...
Post-trip length      float64
Post-trip duration     object
Total weight          float64
Total linear feet     float64
Total volume          float64
Length: 61, dtype: object

In [3806]:
df['ID 2'].unique()

array([1009616.,      nan, 1009633., 1009669., 1009655., 1009610.,
       1009635., 1009643., 1009650., 1009662., 1009660., 1009664.,
       1009620., 1009615., 1009667., 1009656., 1009626., 1009645.,
       1009651., 1009602., 1009665., 1009636., 1009608., 1009612.,
       1009623., 1009625., 1009606., 1009618., 1009657., 1009644.,
       1009619., 1009646., 1009637., 1009605., 1009649., 1009624.,
       1009627., 1009603., 1009613., 1009668., 1009652., 1009658.,
       1009628., 1009641., 1009634., 1009621., 1009640., 1009604.,
       1009647., 1009611., 1009638., 1009663., 1009653., 1009632.,
       1009609., 1009642., 1009661., 1009629., 1009630., 1009654.,
       1009666., 1009622., 1009617., 1009648., 1009607., 1009639.,
       1009631., 1009614., 1009659.])

In [3807]:
df.nunique()

ID 2                   68
Unnamed: 1             23
# Trip stops           18
Unnamed: 3            707
# Orders               18
                     ...
Post-trip length        1
Post-trip duration      1
Total weight           67
Total linear feet       1
Total volume            1
Length: 61, dtype: int64

In [3808]:
df.count()

ID 2                   68
Unnamed: 1            832
# Trip stops           68
Unnamed: 3            832
# Orders               68
                     ...
Post-trip length       68
Post-trip duration     68
Total weight           68
Total linear feet      68
Total volume           68
Length: 61, dtype: int64

In [3809]:
df['Motor vehicle ID'].value_counts()

Queen  (3)     4
Queen  (1)     4
Queen  (6)     4
Queen  (5)     4
Queen  (7)     4
Queen  (11)    4
Queen  (12)    4
Queen  (4)     4
Queen  (2)     4
Queen  (10)    4
Queen  (16)    4
Queen  (15)    4
Queen  (9)     4
Queen  (14)    4
Queen  (8)     4
Queen  (13)    4
Queen  (17)    4
Name: Motor vehicle ID, dtype: int64

In [3810]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID 2                          68 non-null     float64
 1   Unnamed: 1                    832 non-null    object
 2   # Trip stops                  68 non-null     float64
 3   Unnamed: 3                    832 non-null    object
 4   # Orders                      68 non-null     float64
 5   Unnamed: 5                    832 non-null    object
 6   Motor vehicle ID              68 non-null     object
 7   Assignment                    68 non-null     float64
 8   Unnamed: 8                    832 non-null    object
 9   Trailer ID                    0 non-null      float64
 10  Unnamed: 10                   832 non-null    object
 11  Vehicle type                  68 non-null     object
 12  Unnamed: 12                   832 non-null    object
 13  Weight                        68 non-null     float64
 14  Unnamed: 14                   832 non-null    object
 15  % Weight                      68 non-null     float64
 16  Linear feet                   68 non-null     float64
 17  Unnamed: 17                   832 non-null    object
 18  Volume                        68 non-null     float64
 19  Unnamed: 19                   832 non-null    object
 20  Start time                    68 non-null     datetime64[ns]
 21  Unnamed: 21                   832 non-null    object
 22  End time                      68 non-null     datetime64[ns]
 23  Unnamed: 23                   832 non-null    object
 24  Length                        68 non-null     float64
 25  Duration                      68 non-null     object
 26  Unnamed: 26                   832 non-null    object
 27  Costs                         68 non-null     float64
 28  Driving time                  68 non-null     object
 29  Unnamed: 29                   832 non-null    object
 30  Handling time                 68 non-null     object
 31  Unnamed: 31                   832 non-null    object
 32  Break time                    68 non-null     object
 33  Unnamed: 33                   832 non-null    object
 34  Rest period                   68 non-null     object
 35  Unnamed: 35                   824 non-null    object
 36  Waiting time                  68 non-null     object
 37  Restriction violations        68 non-null     object
 38  Unnamed: 38                   832 non-null    object
 39  Unnamed: 39                   832 non-null    object
 40  Qualifications                0 non-null      float64
 41  PTrip                         68 non-null     float64
 42  Unnamed: 42                   832 non-null    object
 43  Planning status               68 non-null     object
 44  Reply status                  136 non-null    object
 45  Export status                 68 non-null     object
 46  Unnamed: 46                   832 non-null    object
 47  Data status                   68 non-null     object
 48  Unnamed: 48                   832 non-null    object
 49  Motor vehicle license number  0 non-null      float64
 50  Unnamed: 50                   832 non-null    object
 51  Unnamed: 51                   0 non-null      float64
 52  Trailer license number        0 non-null      float64
 53  Shift potential               68 non-null     object
 54  Pretrip length                68 non-null     float64
 55  Pretrip duration              68 non-null     object
 56  Post-trip length              68 non-null     float64
 57  Post-trip duration            68 non-null     object
 58  Total weight                  68 non-null     float64
 59  Total linear feet             68 non-null     float64
 60  Total volume                  68 non-null     float64
dtypes: datetime64[ns](2), float64(21), object(38)
memory usage: 429.0+ KB

# Filldown Stop ID and Motor Vehicle ID

In [3811]:
df['ID 2'].fillna(method='ffill', inplace=True) # fill down the blanks for ID 2 & motor vehicle id
df['Motor vehicle ID'].fillna(method = 'ffill', inplace = True)
df['PTrip'].fillna(method = 'ffill', inplace = True)
df.head()

,ID 2,Unnamed: 1,# Trip stops,Unnamed: 3,# Orders,Unnamed: 5,Motor vehicle ID,Assignment,Unnamed: 8,Trailer ID,Unnamed: 10,Vehicle type,Unnamed: 12,Weight,Unnamed: 14,% Weight,Linear feet,Unnamed: 17,Volume,Unnamed: 19,Start time,Unnamed: 21,End time,Unnamed: 23,Length,Duration,Unnamed: 26,Costs,Driving time,Unnamed: 29,Handling time,Unnamed: 31,Break time,Unnamed: 33,Rest period,Unnamed: 35,Waiting time,Restriction violations,Unnamed: 38,Unnamed: 39,Qualifications,PTrip,Unnamed: 42,Planning status,Reply status,Export status,Unnamed: 46,Data status,Unnamed: 48,Motor vehicle license number,Unnamed: 50,Unnamed: 51,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616.0,NaN,11.0,NaN,9.0,NaN,Queen (3),1.0,NaN,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaN,NaN,2385.0,NaN,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,1009616.0,No,NaN,Arrival,NaN,Site name,Queen (3),NaN,Departure,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,Start of time slot,NaN,2385.0,End of time slot,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009616.0,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,Queen (3),NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1009616.0,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,Queen (3),NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1009616.0,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,Queen (3),NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Move Headers to the top

In [3812]:
for column in df.columns:
    if column.startswith('Unnamed'):
        new_name = df.at[1,column]
        df = df.rename(columns = {column: new_name})
        # Assign Headers to all blank headers

In [3813]:
df.head()

,ID 2,No,# Trip stops,Arrival,# Orders,Site name,Motor vehicle ID,Assignment,Departure,Trailer ID,# Orders,Vehicle type,Pickup weight,Weight,Pickup linear feet,% Weight,Linear feet,Delivery weight,Volume,Delivery linear feet,Start time,Current weight,End time,Current linear feet,Length,Duration,Distance from release point,Costs,Driving time,Driving time,Handling time,ZIP,Break time,City,Rest period,Road,Waiting time,Restriction violations,Handling time,Start of time slot,Qualifications,PTrip,End of time slot,Planning status,Reply status,Export status,Delay,Data status,Carbon dioxide,Motor vehicle license number,Fuel,NaN,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616.0,NaN,11.0,NaN,9.0,NaN,Queen (3),1.0,NaN,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaN,NaN,2385.0,NaN,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,1009616.0,No,NaN,Arrival,NaN,Site name,Queen (3),NaN,Departure,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,Start of time slot,NaN,2385.0,End of time slot,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009616.0,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,Queen (3),NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1009616.0,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,Queen (3),NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1009616.0,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,Queen (3),NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3814]:

df['ID 2'] = df['ID 2'].astype(str) # change ID to string dtype

# Format Dates and Times

In [3815]:
df['Arrival'] = pd.to_datetime(df['Arrival'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
df['Departure'] = pd.to_datetime(df['Departure'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
df['Start time'] = pd.to_datetime(df['Start time'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
df['End time'] = pd.to_datetime(df['End time'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
df['Start of time slot'] = pd.to_datetime(df['Start of time slot'], format='%Y-%m-%d %H:%M:%S', errors='coerce')
df['End of time slot'] = pd.to_datetime(df['End of time slot'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

In [3816]:
df.head()

,ID 2,No,# Trip stops,Arrival,# Orders,Site name,Motor vehicle ID,Assignment,Departure,Trailer ID,# Orders,Vehicle type,Pickup weight,Weight,Pickup linear feet,% Weight,Linear feet,Delivery weight,Volume,Delivery linear feet,Start time,Current weight,End time,Current linear feet,Length,Duration,Distance from release point,Costs,Driving time,Driving time,Handling time,ZIP,Break time,City,Rest period,Road,Waiting time,Restriction violations,Handling time,Start of time slot,Qualifications,PTrip,End of time slot,Planning status,Reply status,Export status,Delay,Data status,Carbon dioxide,Motor vehicle license number,Fuel,NaN,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616.0,NaN,11.0,NaT,9.0,NaN,Queen (3),1.0,NaT,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaT,NaN,2385.0,NaT,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,1009616.0,No,NaN,NaT,NaN,Site name,Queen (3),NaN,NaT,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,NaT,NaN,2385.0,NaT,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009616.0,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,Queen (3),NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1009616.0,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,Queen (3),NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1009616.0,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,Queen (3),NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Format Stop ID

In [3817]:
def remove_decimal(value):
    if isinstance(value, str) and value.endswith(".0"):
        return value[:-2]  # Remove the last two characters ".0"
    else:
        return value  # Return unchanged if not a string ending with ".0"

# Apply the custom function to the 'ID 2' column
df['ID 2'] = df['ID 2'].apply(remove_decimal)

In [3818]:
df.head()

,ID 2,No,# Trip stops,Arrival,# Orders,Site name,Motor vehicle ID,Assignment,Departure,Trailer ID,# Orders,Vehicle type,Pickup weight,Weight,Pickup linear feet,% Weight,Linear feet,Delivery weight,Volume,Delivery linear feet,Start time,Current weight,End time,Current linear feet,Length,Duration,Distance from release point,Costs,Driving time,Driving time,Handling time,ZIP,Break time,City,Rest period,Road,Waiting time,Restriction violations,Handling time,Start of time slot,Qualifications,PTrip,End of time slot,Planning status,Reply status,Export status,Delay,Data status,Carbon dioxide,Motor vehicle license number,Fuel,NaN,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616,NaN,11.0,NaT,9.0,NaN,Queen (3),1.0,NaT,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaT,NaN,2385.0,NaT,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,1009616,No,NaN,NaT,NaN,Site name,Queen (3),NaN,NaT,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,NaT,NaN,2385.0,NaT,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009616,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,Queen (3),NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1009616,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,Queen (3),NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1009616,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,Queen (3),NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Rename columns

In [3819]:
df.rename(columns={'No': 'Stop #'}, inplace=True)

In [3820]:
df.head()

,ID 2,Stop #,# Trip stops,Arrival,# Orders,Site name,Motor vehicle ID,Assignment,Departure,Trailer ID,# Orders,Vehicle type,Pickup weight,Weight,Pickup linear feet,% Weight,Linear feet,Delivery weight,Volume,Delivery linear feet,Start time,Current weight,End time,Current linear feet,Length,Duration,Distance from release point,Costs,Driving time,Driving time,Handling time,ZIP,Break time,City,Rest period,Road,Waiting time,Restriction violations,Handling time,Start of time slot,Qualifications,PTrip,End of time slot,Planning status,Reply status,Export status,Delay,Data status,Carbon dioxide,Motor vehicle license number,Fuel,NaN,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
0,1009616,NaN,11.0,NaT,9.0,NaN,Queen (3),1.0,NaT,NaN,NaN,Queen,NaN,5946.0,NaN,0.2973,0.0,NaN,0.0,NaN,2023-01-23 06:00:00,NaN,2023-01-23 11:23:56,NaN,177.0,05:23:56,NaN,0.0,03:23:56,NaN,02:00:00,NaN,00:00:00,NaN,00:30:00,NaN,00:00:00,;,NaN,NaT,NaN,2385.0,NaT,Checked,In planning,New,NaN,-,NaN,NaN,NaN,NaN,NaN,07:03:17,0.0,00:00:00,0.0,00:00:00,5946.0,0.0,0.0
1,1009616,No,NaN,NaT,NaN,Site name,Queen (3),NaN,NaT,NaN,# Orders,NaN,Pickup weight,NaN,Pickup linear feet,NaN,NaN,Delivery weight,NaN,Delivery linear feet,NaT,Current weight,NaT,Current linear feet,NaN,NaN,Distance from release point,NaN,NaN,Driving time,NaN,ZIP,NaN,City,NaN,Road,NaN,NaN,Handling time,NaT,NaN,2385.0,NaT,NaN,Restriction violations,NaN,Delay,NaN,Carbon dioxide,NaN,Fuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1009616,0,NaN,2023-01-23 06:00:00,NaN,Queen Foods,Queen (3),NaN,2023-01-23 06:30:00,NaN,9,NaN,5946.07,NaN,0,NaN,NaN,0,NaN,0,NaT,5946.07,NaT,0,NaN,NaN,0,NaN,NaN,00:00:00,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:30:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1009616,1,NaN,2023-01-23 07:46:44,NaN,Hong Kong Express - 10 am,Queen (3),NaN,2023-01-23 07:56:44,NaN,1,NaN,0,NaN,0,NaN,NaN,554.78,NaN,0,NaT,5391.29,NaT,0,NaN,NaN,69.300286,NaN,NaN,01:16:44,NaN,64093,NaN,Warrensburg,NaN,S Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1009616,2,NaN,2023-01-23 07:58:58,NaN,Ping Hibachi - Warrensburg,Queen (3),NaN,2023-01-23 08:08:58,NaN,1,NaN,0,NaN,0,NaN,NaN,515.86,NaN,0,NaT,4875.43,NaT,0,NaN,NaN,0.460436,NaN,NaN,00:02:14,NaN,64093,NaN,Warrensburg,NaN,N Maguire St,NaN,NaN,00:10:00,2023-01-23 06:00:00,NaN,2385.0,2023-01-23 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Remove unwanted columns

In [3821]:
mask = (df['Stop #'].notna()) & (df['Stop #'] != "No")
df = df[mask]

In [3822]:
df.tail()

,ID 2,Stop #,# Trip stops,Arrival,# Orders,Site name,Motor vehicle ID,Assignment,Departure,Trailer ID,# Orders,Vehicle type,Pickup weight,Weight,Pickup linear feet,% Weight,Linear feet,Delivery weight,Volume,Delivery linear feet,Start time,Current weight,End time,Current linear feet,Length,Duration,Distance from release point,Costs,Driving time,Driving time,Handling time,ZIP,Break time,City,Rest period,Road,Waiting time,Restriction violations,Handling time,Start of time slot,Qualifications,PTrip,End of time slot,Planning status,Reply status,Export status,Delay,Data status,Carbon dioxide,Motor vehicle license number,Fuel,NaN,Trailer license number,Shift potential,Pretrip length,Pretrip duration,Post-trip length,Post-trip duration,Total weight,Total linear feet,Total volume
895,1009659,4,NaN,2023-01-27 11:11:26,NaN,"LB Pop KS, LLC - Popeyes #12179",Queen (11),NaN,2023-01-27 11:21:26,NaN,1,NaN,0,NaN,0,NaN,NaN,832.2,NaN,0,NaT,3726.7,NaT,0,NaN,NaN,33.300525,NaN,NaN,00:38:55,NaN,66046,NaN,Lawrence,NaN,Iowa St,NaN,NaN,00:10:00,2023-01-27 06:00:00,NaN,689.0,2023-01-27 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,1009659,5,NaN,2023-01-27 11:56:40,NaN,Red Fortune - Bonner Spring 9:00 am,Queen (11),NaN,2023-01-27 12:06:40,NaN,1,NaN,0,NaN,0,NaN,NaN,360,NaN,0,NaT,3366.7,NaT,0,NaN,NaN,28.474956,NaN,NaN,00:35:14,NaN,66012,NaN,Bonner Springs,NaN,Oak St,NaN,NaN,00:10:00,2023-01-27 06:00:00,NaN,689.0,2023-01-27 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,1009659,6,NaN,2023-01-27 12:27:00,NaN,Tacos El Sobrino (Park On Street),Queen (11),NaN,2023-01-27 12:37:00,NaN,1,NaN,0,NaN,0,NaN,NaN,288.35,NaN,0,NaT,3078.35,NaT,0,NaN,NaN,16.345791,NaN,NaN,00:20:20,NaN,66102,NaN,Kansas City,NaN,State Ave,NaN,NaN,00:10:00,2023-01-27 06:00:00,NaN,689.0,2023-01-27 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,1009659,7,NaN,2023-01-27 12:45:19,NaN,China Town Buffet - 18th,Queen (11),NaN,2023-01-27 12:55:19,NaN,1,NaN,0,NaN,0,NaN,NaN,3078.35,NaN,0,NaT,0,NaT,0,NaN,NaN,1.723062,NaN,NaN,00:08:19,NaN,66102,NaN,Kansas City,NaN,S 18th St,NaN,NaN,00:10:00,2023-01-27 06:00:00,NaN,689.0,2023-01-27 18:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,1009659,8,NaN,2023-01-27 13:00:45,NaN,Queen Foods,Queen (11),NaN,2023-01-27 13:00:45,NaN,0,NaN,0,NaN,0,NaN,NaN,0,NaN,0,NaT,0,NaT,0,NaN,NaN,1.716849,NaN,NaN,00:05:26,NaN,66105,NaN,Kansas City,NaN,S 14th St,NaN,NaN,00:00:00,2023-01-27 06:00:00,NaN,689.0,2023-01-27 19:00:00,NaN,NaN,NaN,00:00:00,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3823]:
df = df.dropna(axis=1, how='all')
df = df.loc[:, (df != 0).any(axis=0)]

In [3824]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00

In [3825]:
unique_count_routes = df['ID 2'].nunique()
unique_count_dates = df['Departure'].nunique()

In [3826]:
for id, row in df.iterrows():
    print(str(id) + ' :' + row['Site name'])

2 :Queen Foods
3 :Hong Kong Express - 10 am
4 :Ping Hibachi - Warrensburg
5 :Sabai Thai - Warrensburg
6 :King's Chef -  Warrensburg
7 :PHO-4U - Warrensburg
8 :New Oriental Cusine - Opens 9:30am
9 :MAMA PIN'S THAI  10AM
10 :Chinese Buffet - Higginsville
11 :Lucky Dragon *****
12 :Queen Foods
15 :Queen Foods
16 :LB Pop KS, LLC - Popeyes #4821
17 :LB Pop KS, LLC - Popeyes #14089
18 :China Star Super Buffet - Raymore
19 :Sunrise  **** Harrisonville
20 :Mr. Sushi - Lee's Summit
21 :China Dragon J - L.S.
22 :LB Pop KS, LLC - Popeyes #8562
23 :Shanghai Express-Raytown 9:30am
24 :Cosentino's Price Chopper #106
25 :Cosentino's Price Chopper #105 C
26 :Steam Bowl - KC    8 AM
27 :Gringo Loco - KC   7:30am
28 :Queen Foods
31 :Queen Foods
32 :Waldo Thai Place 10 AM
33 :LB Pop KS, LLC - Popeyes #3628
34 :LB Pop KS, LLC - Popeyes #3114
35 :Kin Lin *****
36 :Bo Lings - Plaza  8:30am
37 :Wings Cafe  - Broadway 10 AM
38 :LB Pop KS, LLC - Popeyes #2843
39 :Baramee Thai Bistro 10:30 AM
40 :Queen Foods
43 :Queen Foods
44 :Old Wok - Barry Rd *****
45 :Tasty Thai - Liberty
46 :Penguin's Kitchen - Liberty
47 :Cosentino's Price Chopper #120
48 :Hunan Garden - Kearney 10am
49 :Hunan Garden - ES
50 :King's Garden - Richmond
51 :Golden Leaf - ES ********
52 :Cosentino's Price Chopper #288
53 :Kam Sheng
54 :Vietnam Cafe  - Campbell  8:00 am.
55 :Golden Hearts Care 7:30 AM
56 :Queen Foods
59 :Queen Foods
60 :Bo Ling(G) - Zona Rosa 10:30am
61 :GB Chinese - # 11 (Price Chopper)
62 :Wings Cafe - Englewood Rd 10:30
63 :LB Pop KS, LLC - Popeyes #2691
64 :Hunan Garden - Gladstone 9:30am
65 :China Dragon - Gladstone 11:00am
66 :K.C. Wings - Gladstone
67 :Hong's Buffet - Barry Rd. 9:30am
68 :China Wok - Barry Rd. 9:30 am
69 :Rainbow - Barry Rd ******
70 :LB Pop KS, LLC - Popeyes #12358
71 :Queen Foods
74 :Queen Foods
75 :China Town Cafe - Blue Springs
76 :LB Pop KS, LLC - Popeyes #12359
77 :Legend Of Asia - Blue Springs
78 :China Buffet- Oak Grove "Don't Drop
79 :China Buffet -  Odessa
80 :Thailand - Blue Springs
81 :China Kitchen - Blue Springs
82 :Golden Rice - Independence
83 :Mandarin House ****66
84 :Daisy's Mexican # 2
85 :LB Pop KS, LLC - Popeyes #10328
86 :Queen Foods
89 :Queen Foods
90 :Chosun Korean BBQ 2   10AM
91 :Pine and Bamboo Garden - 9:00 am
92 :KC Buffet - Shawnee
93 :Rice House - Lenexa
94 :ABC Cafe
95 :Bangkok Pavilion - 9:30 am
96 :Bo Ling - Metcalf
97 :Dragon Inn - OP (open 10:20 am)
98 :China Town - OP
99 :Thai Orchid - Mission   8:30AM
100 :Sushi Karma Asian Bistro 10:30 AM
101 :China Star - Roeland Park
102 :Queen Foods
105 :Queen Foods
106 :China Town  Buffet - 18th
107 :Tacos El Sobrino  (Park On Street)
108 :Panda King Express
109 :Delicias De Honduras 10am
110 :Daisy's Mexican Food - 7 AM
111 :EL CAMINO REAL #2 -- Don't drop!!
112 :Queen Foods
115 :Queen Foods
116 :LB Pop KS, LLC - Popeyes #12128
117 :LB Pop KS, LLC - Popeyes #12778
118 :LB Pop KS, LLC - Popeyes #12606
119 :Zhuba Pop Foods, LLC-Popeyes #13396
120 :HZ OPS Holding, Inc-Popeyes #13155
121 :Zhuba Pop Foods, LLC-Popeyes #2693
122 :Zhuba Pop Foods, LLC-Popeyes #13675
123 :HZ OPS Holding, Inc-Popeyes #12759
124 :Zhuba Pop Foods, LLC-Popeyes #13156
125 :HZ OPS Holding, Inc-Popeyes #12826
126 :HZ OPS Holding, Inc-Popeyes #5967
127 :HZ OPS Holding, Inc-Popeyes #12296
128 :TA Operating LLC - Popeyes #10605
129 :Queen Foods
132 :Queen Foods
133 :HZ OPS Holding, Inc-Popeyes #12758
134 :HZ OPS Holding, Inc-Popeyes #12300
135 :HZ OPS Holding, Inc-Popeyes #12294
136 :HZ OPS Holding, Inc-Popeyes #2508
137 :HZ OPS Holding, Inc-Popeyes #2506
138 :HZ OPS Holding, Inc-Popeyes #2553
139 :HZ OPS Holding, Inc-Popeyes #2780
140 :HZ OPS Holding, Inc-Popeyes #4277
141 :Zhuba Pop Foods, LLC-Popeyes #3801
142 :HZ OPS Holding, Inc-Popeyes #12295
143 :Zhuba Pop Foods, LLC-Popeyes #13459
144 :HZ OPS Holding, Inc-Popeyes #12762
145 :Zhuba Pop Foods, LLC-Popeyes #13521
146 :Queen Foods
149 :Queen Foods
150 :China Inn - *****Lenexa
151 :Fortune Wok - 135th St
152 :Thai House - O.P. 11AM
153 :Magic Noodle - O.P.
154 :Yummy Chinese - OP
155 :Fortune Wok - Metcalf - OP
156 :Pad  Thai - Metcalf
157 :Bo Ling - 135th
158 :Pan-Asia Market   OP  9am
159 :Szechuan Dynasty (New) - 10:30am
160 :Queen Foods
163 :Queen Foods
164 :Bo Ling - Lenexa
165 :GB Chinese #34 ( Hen House)
166 :LB Pop KS, LLC - Popeyes #12360
167 :Tortillas De Campo LLC - Olathe
168 :Spring Of China  *****Paola
169 :Golden Palace- 10:20 am Don't Drop
170 :Tea Garden - Olathe 11 am
171 :Asian  Pearl - Olathe
172 :Queen Foods
175 :Queen Foods
176 :China Buffet - KC ******
177 :Yuki Japanese - Topeka
178 :Mizu Sushi II - Topeka 11:00 AM
179 :Meat Market Camecuaro - Topeka 9 AM
180 :Kobe Japanese Steakhouse - Lawrence
181 :Red Pepper - Lawrence
182 :LB Pop KS, LLC - Popeyes #12179
183 :Encore Cafe - Lawrence
184 :Queen Foods
187 :Queen Foods
188 :Cosentino's Price Chopper #249
189 :Cosentino's Price Chopper #285
190 :Cosentino's Price Chopper #250
191 :Cosentino's Price Chopper #404
192 :Dragon Wok - Omaha******
193 :Supermart EL TORITO INC. Opens 8am
194 :Queen Foods
197 :Queen Foods
198 :Spices Asian
199 :New China Star *****
200 :Chinese Garden -10 am  Claycomo
201 :Hunan Garden - Liberty  8:45 am
202 :China Town Express Of KC
203 :Tasty Thai - KC
204 :China Gourmet - Riverside
205 :Tao Tao  11am
206 :China Town  Buffet - 18th
207 :Queen Foods
210 :Queen Foods
211 :Elviras Bakery
212 :Chang's Wok - Opens 10:30am
213 :Bonito Michoacan Bakery (Olathe)
214 :Wong's Kitchen - Olathe
215 :Niji Sushi & Steak -- Open 11:00am
216 :Bo Bo - Olathe 10:30am DON'T drop!
217 :Jasmine Pavilion - Olathe
218 :Thai Zappz   O.P.  11 AM - 3 PM
219 :Hot Basil - OP  10:15 - 2:00 PM
220 :Sawasdee Thai Cuisine - O.P.
221 :Queen Foods
224 :Queen Foods
225 :Bonito Michoacan Bakery KC
226 :Phikul Thai Bistro - 10:15  AM
227 :Baramee Thai Bistro 10:30 AM
228 :Linwood Chinese(G)
229 :Cozy Thai   10 AM
230 :Happy Dragon - 103rd St
231 :Friendship One
232 :Cosentino's Market Brookside #144
233 :Lucky  Dynasty   -  10:30  AM
234 :Moti Mahal - Penn.  #2
235 :Genghis Khan II 10:00am
236 :Aloha Chopstick - K.C.
237 :Vietnam Cafe - KCKS
238 :Queen Foods
241 :Queen Foods
242 :Hunan  - Cameron  ****
243 :Grand Wok Inc. - Shawnee
244 :Hibachi GO Steak & Sushi
245 :Fortune Palace - Lenexa
246 :Moon Wok
247 :Oriental Market  Kansas
248 :Cosentino's Price Chopper #121
249 :Thai Place - 87TH    10 am
250 :New China Town - Mission
251 :Queen Foods
254 :Queen Foods
255 :AAFES - Popeyes #11999 Ft Leonard
256 :Queen Foods
259 :Queen Foods
260 :Tsing Tao - SOUTH
261 :Sam Fine Foods Eggrolls (11am- 2pm)
262 :Nut Pob - Des Moines 9am
263 :Mr. Eggroll - D.M.- Do NOT Drop !!
264 :China Chef--DM 9:30am (DON'T DROP)
265 :JJ Jasmine Thai  - D.M. (9 - 2pm)
266 :Rolling Wok Cafe -10 AM - 2 PM
267 :Tsing Tsao - EAST  9AM Don't Drop
268 :THAI FLAVORS - D.M. ( 10 AM - 2 PM)
269 :Fawn's Asian Cuisine   10:45 AM
270 :China Place - DM *****
271 :Mojitos Mexican Grill - 9AM
272 :Wong's Chopsticks*** Johnston
273 :De Rice - Johnston  ***
274 :Mandarin Noodle House -Johnston ***
275 :Shanghai - Waukee  ****
276 :Spices Asian
277 :Queen Foods
280 :Queen Foods
281 :Cosentino's Market Downtown #284
282 :Mr. Sushi - Lee's Summit
283 :Mali Thai Bistro - Lee's Summit
284 :Lucky Wok - Lees Summit
285 :Cosentino's Price Chopper #171
286 :THAI SUBMONGKOL NAKA  10 AM
287 :Taste Of China - Raymore
288 :Chinese Wok - Belton DON'T DROP!!!!
289 :Manila Bay Express - Grandview 11am
290 :Queen Foods
293 :Queen Foods
294 :Tianluo Bistro - Wichita
295 :Nori Japanese *** Wichita
296 :Asian Wok -Wichita Open 8AM
297 :Fried Rice - Wichita   10 AM
298 :Kan-Grow Sprouts LLC - Wichita
299 :Pho Special - Wichita 8AM
300 :Wok Hey - Wichita  *** 3168
301 :Hibachi Boy Central LLC ****
302 :Great Wall - Maple ***Put in cooler
303 :Pho Chopstick - Wichita ****
304 :Emperor Japanese Grill ***AA 9005
305 :Kimlan Sandwiches ( Don't drop)
306 :Dragon Express-Wichita ****
307 :Asian Bistro - Wichita  ****   9 AM
308 :Asian Cuisines ****Grimes
309 :Queen Foods
312 :Queen Foods
313 :Banana Leaf Asian Bistro
314 :Shang Yuen - D.M.
315 :Lucky Lotus - Ingersoll   8 AM
316 :Lina's Mexican Rest. Des Moines 9am
317 :THAI FLAVORS  -   INGERSOLL  ****
318 :Jade Garden- Ankeny  9:30 AM
319 :Lucky Bamboo -Ankeny  Do NOT Drop!!
320 :Pho 85 -- Ankeny *****
321 :Siam Table - Ankeney **** 71
322 :SILK ELEPHANT - ANKENY  *****
323 :Tacos La Familia - Des Moines 9 AM
324 :Taki Japanese - Urbandale *****
325 :Cool Basil - Clive  10:00 - 2:30 PM
326 :Hans Golden Dragon ****- Bellevue
327 :Queen Foods
330 :Queen Foods
331 :Thai Kitchen - Independence
332 :Canton Chinese - Raytown
333 :Hacienda Vieja
334 :China Town Cafe - Blue Springs
335 :Cosentino's Sun Fresh #161
336 :Los Amigos Restaurant - Indepence
337 :Carniceria Leon - open 7 AM
338 :Gringo Loco - KC   7:30am
339 :Carniceria Y Tortilleria DonAntonio
340 :Queen Foods
343 :Queen Foods
344 :El Rinconcito Salvadoreño de KC
345 :Tacos El Gordo
346 :Blue Sky Asian Market
347 :Taqueria Arandas
348 :Baan Thai #1 - Leavenworth  9 AM
349 :Young Dragon  - Atchison 10:15am
350 :Hornbill Asian Market - St Joseph
351 :Hunan - St. Joseph
352 :Twins Dragon - St. Joseph
353 :Red Dragon - Platte City 10:00 am
354 :Moti Mahal - Barry Rd.  9 - 2 PM
355 :New China Wok Inc.
356 :Queen Foods
359 :Queen Foods
360 :Mariscos Cheli   **** Wichita
361 :Dragon Wok Express - Gretna
362 :Taipei Asian Cuisine ***new
363 :Panda House - Omaha **Ye**
364 :D'leons - L St. ( Do not Drop !! )
365 :Lao's Thai - Omaha  * Don't  Drop *
366 :Shang Hai Garden - Omaha  B4  NOON
367 :D'leon's - Saddle Creek
368 :CajunCrab Pho 10:30
369 :Saigon Surface -Omaha (Close 2:30)
370 :Panda House 16th St- Omaha
371 :China Wok - Council Bluff
372 :Taste Of China - Council Bluff
373 :Great Wall Express - Woodburry
374 :Great Wall Express - Broadway
375 :Queen Foods
378 :Queen Foods
379 :Jade Palace **2** Bellevue
380 :Crystal Jade - Omaha ******
381 :Blue & Fly Asian Kitchen********
382 :ZOU Bistro - Omaha 9 AM
383 :Golden Palace ***-- Omaha
384 :Asian Wok - 10:30am   DON'T DROP
385 :China Buffet - Omaha  ***5***
386 :D'Leon's Mexican Food - Davenport
387 :China Wok - Omaha
388 :JJ CHINA - Omaha Don't drop!!!
389 :Gold Mountain *** -Aksarben Village
390 :China Taste - Gardner  *******
391 :Queen Foods
394 :Queen Foods
395 :China Town  Buffet - 18th
396 :Carniceria Y Tortilleria DonAntonio
397 :Rice Bowl - K.C. 10:30am
398 :Tacos El Gordo
399 :Gorditas Durango - 7am
400 :Queen Foods
403 :Queen Foods
404 :Buck Tui BBQ
405 :Oriental Market  Kansas
406 :Jarocho - State Line 10am
407 :China Inn - *****Lenexa
408 :Lanna Thai - Lenexa 10:30 - 3:00
409 :Queen Foods
412 :Queen Foods
413 :Hong Kong - Nebraska
414 :China House - Lincoln - 10:50 am
415 :Magic Wok - Lincoln
416 :D'leons Chelita - O ST
417 :Egg Roll King - Lincoln
418 :D'Leons - 70th St.
419 :Ming House - Lincoln 10:30 am
420 :D'Leons - 48th St.
421 :D'leons Taco Rico - Lincoln   6 PM
422 :Rolling Wok *** - Lincoln
423 :China Garden - Lincoln 11:00 am
424 :Mr. Hui's #2****
425 :Queen Foods
428 :Queen Foods
429 :Ipho Tower - Broadway
430 :Waldo Thai Place 10 AM
431 :Queen Foods
434 :Queen Foods
435 :Lucky Dragon *****
436 :Cosentino's Price Chopper #105 C
437 :Los Amigos Restaurant - Indepence
438 :Wing Lee  *** 1522 EZ1
439 :China Town Cafe - Blue Springs
440 :Tokyo Grill - Blue Springs
441 :China 88 - Lee's Summit
442 :Mali Thai Bistro - Lee's Summit
443 :Cosentino's Price Chopper #250
444 :Chinese Wok - Belton DON'T DROP!!!!
445 :Queen Foods
448 :Queen Foods
449 :D'Leon's Taco Rico - 27th St.
450 :Taqueria Limon Food Truck
451 :Mr. Hui - Lincoln 11:00 am
452 :Green Farms Dai PHAT MARKET
453 :OISHII Japanese Steakhouse  Lincoln
454 :Perfect Diner - Lincoln 11:00 am
455 :Dias D'leon - 27th St.
456 :New Market - Lincoln 10:30 AM
457 :Vung Tau - Lincoln  8 am
458 :Golden Wok - Lincoln 10:30 am
459 :Lobo's City Mex Market -Lincoln 9AM
460 :VIET HAO MARKET - Lincoln 10 AM
461 :El Chaparro Mexican Food
462 :Blue Orchid - Lincoln  1 PM
463 :Pan Dulce - Lincoln 6 am
464 :Queen Foods
467 :Queen Foods
468 :Supermart EL TORITO INC. Opens 8am
469 :Cosentino's Price Chopper #359
470 :Cosentino's Price Chopper #285
471 :Cosentino's Price Chopper #104
472 :Los Amigos Restaurant - Indepence
473 :Cosentino's Price Chopper #120
474 :Queen Foods
477 :Queen Foods
478 :Lotus Express - Fort Scott  ***
479 :China Palace -IOLA **M1 USA
480 :Eastern - Chanute ***41322
481 :Little China - Chanute ***26445
482 :Peter's  ***
483 :Great China  - Independence 8am
484 :Shanghai Garden - Indepen. 8am
485 :EL VAQUERRO - JOPLIN
486 :Lucy's - Joplin 9 AM
487 :Lotus Xpress - Joplin 10 am
488 :Thai Time Cafe - 10:30 am
489 :Lotus Garden - Joplin
490 :Fortune Korean/Thai
491 :Happy Family  -  Pittsburg
492 :Oriental Star - Pittsburg
493 :Fernandez Market - PITTSBURG
494 :Queen Foods
497 :Queen Foods
498 :Monkey King - Lexana
499 :China Taste - Gardner  *******
500 :Cosentino's Price Chopper #405
501 :China One - Olathe
502 :Pho Sai Gon - OP
503 :Kababesh Bar & Grill - OP
504 :Cosentino's Price Chopper #102
505 :Queen Foods
508 :Queen Foods
509 :Taste Place - Columbia
510 :SHWE MARKET INT'L FOODS 9 am
511 :Hong Kong Market - Columbia 9:00 am
512 :New China  - Ashland
513 :Go Fresco LLC - Columbia  9AM
514 :Tiger Chef - Columbia  12:00
515 :Peking - Columbia ***Hillman S22
516 :Pho  Quan - Columbia 10:30
517 :Quickway Japanese Hibachi
518 :Chim's Thai Kitchen - Columbia
519 :House Of Chow - Columbia  10 - 2 PM
520 :New China - Marshall
521 :China Inn - Marshall
522 :Joyous China - Marshall
523 :Queen Foods
526 :Queen Foods
527 :Maria's # 3 - Clive  7:00 am
528 :Queen Foods
531 :Queen Foods
532 :New China - SP
533 :New Oriental ****- Springfield
534 :Rice House #2 *** SP 19281
535 :Rama Thai Cafe - 9:30am
536 :Bambu Vietnamese Cuisine - SP
537 :Happy China - *** SP
538 :Yum Yum Bowl - SP
539 :Asian World market
540 :Everyday Thai - 10AM - 3 PM
541 :Pho Kim **** Springfield
542 :China King - Springfield  *Drop*
543 :Panda Inn & Asian Fusin
544 :Cashew Inn ***Cashew Out
545 :Thailand Station - Springfield 8 AM
546 :Wayo Japan Sushi Bar - 10:30am
547 :Peking House -Springfield ****
548 :Asian Hut - Springfield ******
549 :Little Tokyo - SP
550 :Asianfy Hibachi - Clinton ***
551 :China House *** Clinton
552 :Queen Foods
555 :Queen Foods
556 :Cosentino's Price Chopper #416
557 :Cosentino's Price Chopper #415
558 :Cosentino's Sun Fresh New Mark #156
559 :Lotus Hot Pot & Grill - 12 PM
560 :GB Chinese - # 11 (Price Chopper)
561 :CMC FOODS, INC.  -- Close at 3 PM
562 :Queen Foods
565 :Queen Foods
566 :CMC FOODS, INC.  -- Close at 3 PM
567 :Hunan Garden - Gladstone 9:30am
568 :Tasty Thai - Liberty
569 :Tacos El Tio - 9:30 AM
570 :Daisy's Mexican Food - 7 AM
571 :Queen Foods
574 :Queen Foods
575 :Sakura - Olathe (close at 2PM)
576 :Fortune Wok - 135th St
577 :Pho Vietnam - O.P.(Don't drop)
578 :Jumbo Noodle Bar
579 :Cosentino's Market #425
580 :Miyabi Japanese & Asian Bistro
581 :Fortune Wok - Metcalf - OP
582 :CM CHICKEN - O.P. 11 AM
583 :Queen Foods
586 :Queen Foods
587 :Oishi Sushi - Shawnee
588 :Queen Foods
591 :Queen Foods
592 :Oriental Garden - Raymore
593 :China Wok  - Harrisonville 10:45 AM
594 :Tokyo Grill - Rain Tree
595 :Tokyo Grill - Lee's Summit
596 :Mr. Sushi - Lee's Summit
597 :China Dragon J - L.S.
598 :Shanghai Express-Raytown 9:30am
599 :Queen Foods
602 :Queen Foods
603 :Oishi Sushi - Shawnee
604 :KC Buffet - Shawnee
605 :Dragon Inn - OP (open 10:20 am)
606 :Thai Place - 87TH    10 am
607 :Bangkok Pavilion - 9:30 am
608 :Thai Orchid - Mission   8:30AM
609 :Sushi Karma Asian Bistro 10:30 AM
610 :Queen Foods
613 :Queen Foods
614 :Cosentino's Sun Fresh #161
615 :Queen Foods
618 :Queen Foods
619 :Jasmin - Eudora 8:30 am
620 :Little Saigon Cafe - Lawrence 7:30
621 :Tryyaki - Lawrence ****
622 :Red Pepper - Lawrence
623 :Tortilleria Juan - Topeka 8 AM
624 :Meat Market Camecuaro - Topeka 9 AM
625 :Mayte Cazares
626 :Green Tea Sushi - Manhattan
627 :Tasty China House ***Manhattan
628 :Baan Thai # 2 Manhattan
629 :Asian Market - Manhattan
630 :Panda Palace - Junction City
631 :Family Buffet - Junction City
632 :Kiku Steak House - Topeka
633 :Seabrook Apple Market - Topeka 6 AM
634 :Saigon - Topeka 9:00 AM
635 :Queen Foods
638 :Queen Foods
639 :EL CAMINO REAL #2 -- Don't drop!!
640 :Bo Lings - Plaza  8:30am
641 :SANKOFA CAFE    8:30 AM
642 :Baramee Thai Bistro 10:30 AM
643 :Queen Foods
646 :Queen Foods
647 :Spices Asian
648 :China Wok - Barry Rd. 9:30 am
649 :Rainbow - Barry Rd ******
650 :Saki Asian - 64th St
651 :Queen Foods
654 :Queen Foods
655 :Lucky Buffet -Opens 10:00 am
656 :Golden Rice - Independence
657 :Peking Express - Sugar Creek  12 PM
658 :Wing Lee  *** 1522 EZ1
659 :Gold Lion - Independence
660 :China Town Cafe - Blue Springs
661 :Legend Of Asia - Blue Springs
662 :Golden Eggroll - Blue Springs
663 :China One - Blue Springs  10 am
664 :Queen Foods
667 :Queen Foods
668 :HZ OPS Holding, Inc-Popeyes #12296
669 :HZ OPS Holding, Inc-Popeyes #5967
670 :HZ OPS Holding, Inc-Popeyes #12826
671 :Zhuba Pop Foods, LLC-Popeyes #2693
672 :Zhuba Pop Foods, LLC-Popeyes #13675
673 :HZ OPS Holding, Inc-Popeyes #12759
674 :HZ OPS Holding, Inc-Popeyes #13155
675 :Zhuba Pop Foods, LLC-Popeyes #13396
676 :TA Operating LLC - Popeyes #10605
677 :LB Pop KS, LLC - Popeyes #12606
678 :LB Pop KS, LLC - Popeyes #12778
679 :LB Pop KS, LLC - Popeyes #12128
680 :Queen Foods
683 :Queen Foods
684 :China Buffet  - LW >> DON'T drop
685 :King House-Leavenworth-DO NOT DROP
686 :Young Dragon  - Atchison 10:15am
687 :Rice House - Tonganoxie
688 :Lin's Chinese - Bonner Springs 10AM
689 :Queen Foods
692 :Queen Foods
693 :China Town Cafe - Blue Springs
694 :Queen Foods
697 :Queen Foods
698 :China Go - Woodlawn  ****
699 :Hibachi Boy Central LLC ****
700 :Mariscos El Tucanazo
701 :Ming's - Wichita
702 :Eggroll Express - Wichita
703 :Kan-Grow Sprouts LLC - Wichita
704 :Xing Xing - Wichita 10 AM
705 :PHO KC - WICHITA - DO NOT DROP
706 :Fried Rice - Wichita   10 AM
707 :Lucky Market - Wichita
708 :Nori Japanese *** Wichita
709 :China Go Grill -  Rock Road
710 :Kim's Noodle Bar & Grill
711 :Beijing - El Dorado
712 :House of Ma  - DO NOT DROP!!!!
713 :Ichiban Asian Bistro - Emporia
714 :Queen Foods
717 :Queen Foods
718 :Los Alamos Market
719 :Angela's Bakery - Springdale 6am
720 :Mariscos Playa Azul - Springdale
721 :PattayaThai Sushi -Springdale 10am
722 :Supermercado La Michoacana Sprgdale
723 :Taqueria Real Jacona - Rogers
724 :Mi Tienda La Guadalupana - Rogers
725 :Taqueria Michoacan LLC
726 :Lins Garden - Bentonville
727 :Taqueria Michoacan LLC
728 :Maria's - Rogers
729 :Mr. Burrito - Rogers
730 :Viva El Taco - Pea Ridge ****
731 :Fortune Korean/Thai
732 :Queen Foods
735 :Queen Foods
736 :Zubha Pop Foods LLC- Popeyes #10612
737 :HZ OPS Holding, Inc-Popeyes #12300
738 :HZ OPS Holding, Inc-Popeyes #12294
739 :HZ OPS Holding, Inc-Popeyes #2508
740 :Corner 17 - St. Louis  10 AM - 1 PM
741 :HZ OPS Holding, Inc-Popeyes #2506
742 :HZ OPS Holding, Inc-Popeyes #2553
743 :HZ OPS Holding, Inc-Popeyes #2780
744 :Zhuba Pop Foods, LLC-Popeyes #3801
745 :HZ OPS Holding, Inc-Popeyes #12295
746 :Zhuba Pop Foods, LLC-Popeyes #13459
747 :HZ OPS Holding, Inc-Popeyes #12762
748 :Zhuba Pop Foods, LLC-Popeyes #13521
749 :Queen Foods
752 :Queen Foods
753 :Chang's Wok - Opens 10:30am
754 :Novedades El Guero
755 :China Taste - Gardner  *******
756 :China Palace ****Ottawa
757 :Chen Buffet  - Paola ****
758 :Wong's Kitchen - Olathe
759 :Bo Bo - Olathe 10:30am DON'T drop!
760 :LB Pop KS, LLC - Popeyes #12360
761 :Hira's Steak & Sushi - Olathe
762 :Queen Foods
765 :Queen Foods
766 :Supermart EL TORITO INC. Opens 8am
767 :Queen Foods
770 :Queen Foods
771 :Vietnam Cafe  - Campbell  8:00 am.
772 :Bo Ling(G) - Zona Rosa 10:30am
773 :Wings Cafe - Englewood Rd 10:30
774 :LB Pop KS, LLC - Popeyes #2691
775 :China Dragon - Gladstone 11:00am
776 :K.C. Wings - Gladstone
777 :Cosentino's Sun Fresh New Mark #156
778 :LB Pop KS, LLC - Popeyes #12358
779 :Queen Foods
782 :Queen Foods

In [3827]:
df['Time_Difference'] = df['Departure'] - df['Arrival']
df['Duration_Hours'] = df['Time_Difference'].dt.components.hours
df['Duration_Minutes'] = df['Time_Difference'].dt.components.minutes
df['Duration_Seconds'] = df['Time_Difference'].dt.components.seconds

In [3828]:
df.tail()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds
895,1009659,4,2023-01-27 11:11:26,"LB Pop KS, LLC - Popeyes #12179",Queen (11),2023-01-27 11:21:26,1,0,832.2,3726.7,33.300525,00:38:55,66046,Lawrence,Iowa St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0
896,1009659,5,2023-01-27 11:56:40,Red Fortune - Bonner Spring 9:00 am,Queen (11),2023-01-27 12:06:40,1,0,360,3366.7,28.474956,00:35:14,66012,Bonner Springs,Oak St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0
897,1009659,6,2023-01-27 12:27:00,Tacos El Sobrino (Park On Street),Queen (11),2023-01-27 12:37:00,1,0,288.35,3078.35,16.345791,00:20:20,66102,Kansas City,State Ave,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0
898,1009659,7,2023-01-27 12:45:19,China Town Buffet - 18th,Queen (11),2023-01-27 12:55:19,1,0,3078.35,0,1.723062,00:08:19,66102,Kansas City,S 18th St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0
899,1009659,8,2023-01-27 13:00:45,Queen Foods,Queen (11),2023-01-27 13:00:45,0,0,0,0,1.716849,00:05:26,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,689.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0

# Create ArcGIS object

In [3829]:
# Create ArcGIS object
nom = ArcGIS()

In [3830]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0

In [3831]:
#df = df.rename(columns = {'state': 'State'})
df = df.rename(columns = {'zipcode':'Zip'})

In [3832]:
df.head(2)

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0

In [3833]:
# Assuming df1 is your DataFrame with "ID2" and "Stop #" columns
df['unique_identifier'] = df['ID 2'].astype(str) + '-' + df['Stop #'].astype(str)

In [3834]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds,unique_identifier
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009616-0
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-1
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-2
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-3
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-4

In [3835]:
df.shape

(764, 25)

In [3836]:
df['Road'] = df['Road'].combine_first(df['ZIP'])

In [3837]:
df['Road']

2         S 14th St
3      S Maguire St
4      N Maguire St
5       E Culton St
6      N Maguire St
           ...
895         Iowa St
896          Oak St
897       State Ave
898       S 18th St
899       S 14th St
Name: Road, Length: 764, dtype: object

In [3838]:
unique_values = df['Road'].unique()

In [3839]:

df2 = pd.DataFrame({'Unique_Road': unique_values})

In [3840]:
df2.head()

    Unique_Road
0     S 14th St
1  S Maguire St
2  N Maguire St
3   E Culton St
4   E Young Ave

In [3841]:
#unique_values = df2['Unique_Road'].unique()

In [3842]:
#df2_unique = pd.DataFrame({'Unique_Road': unique_values})
#df2_unique.head()

In [3843]:
#df['Road'] = df['Road'].combine_first(df['ZIP'])

In [3844]:
#df2 = pd.DataFrame({'Unique_Road': unique_values})

In [3845]:
df2.head()

    Unique_Road
0     S 14th St
1  S Maguire St
2  N Maguire St
3   E Culton St
4   E Young Ave

In [3846]:

# Assuming df2 is your DataFrame
unique_values = df2['Unique_Road'].astype(str)

In [3847]:
df2= pd.DataFrame({'Unique_Road': unique_values})
df2.head()

    Unique_Road
0     S 14th St
1  S Maguire St
2  N Maguire St
3   E Culton St
4   E Young Ave

In [3848]:
df2['Unique_Road'].dtype

dtype('O')

In [3849]:
df2.shape

(332, 1)

In [3850]:
df['Road']

2         S 14th St
3      S Maguire St
4      N Maguire St
5       E Culton St
6      N Maguire St
           ...
895         Iowa St
896          Oak St
897       State Ave
898       S 18th St
899       S 14th St
Name: Road, Length: 764, dtype: object

In [3851]:
df.tail(50)

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds,unique_identifier
842,1009607,2,2023-01-27 09:37:16,Szechwan Sunrise **** Bellevue,Queen (7),2023-01-27 09:47:16,1,0,657.76,9118.15,3.383988,00:06:39,68123,Bellevue,S 36th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-2
843,1009607,3,2023-01-27 10:00:13,Gold Mountain *** -Aksarben Village,Queen (7),2023-01-27 10:10:13,1,0,164.49,8953.66,8.946502,00:12:57,68138,Omaha,Mercury St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-3
844,1009607,4,2023-01-27 10:21:51,Dragon Wok Express - Gretna,Queen (7),2023-01-27 10:31:51,1,0,200,8753.66,9.450434,00:11:38,68028,Gretna,Nebraska Crossing Dr,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-4
845,1009607,5,2023-01-27 10:48:33,Saigon - Omaha ( W. Center rd.),Queen (7),2023-01-27 11:03:33,1,0,334.1,8419.56,15.773508,00:16:42,68144,Omaha,W Center Rd,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:15:00,0,15,0,1009607-5
846,1009607,6,2023-01-27 11:13:02,Pan Asian Terrace -- Don't Drop!!!!,Queen (7),2023-01-27 11:23:02,1,0,517.47,7902.09,4.293054,00:09:29,68130,Omaha,S 157th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-6
847,1009607,7,2023-01-27 11:33:10,D'Leon's Mexican Food - Davenport,Queen (7),2023-01-27 11:43:10,1,0,200,7702.09,5.056097,00:10:08,68154,Omaha,Davenport St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-7
848,1009607,8,2023-01-27 11:50:51,Asian Wok - 10:30am DON'T DROP,Queen (7),2023-01-27 12:00:51,1,0,398.7,7303.39,4.140818,00:07:41,68134,Omaha,N 90th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-8
849,1009607,9,2023-01-27 12:07:37,ZOU Bistro - Omaha 9 AM,Queen (7),2023-01-27 12:37:37,2,0,3383.42,3919.97,2.706693,00:06:46,68114,Omaha,N 76th St,00:20:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:30:00,0,30,0,1009607-9
850,1009607,10,2023-01-27 12:39:21,Blue & Fly Asian Kitchen********,Queen (7),2023-01-27 12:49:21,1,0,388.6,3531.37,0.549292,00:01:44,68114,Omaha,S 72nd St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-10
851,1009607,11,2023-01-27 13:02:01,Dragon Cafe **Ye**- La Vista,Queen (7),2023-01-27 13:12:01,1,0,674.95,2856.42,5.770053,00:12:40,68128,La Vista,S 84th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-11
852,1009607,12,2023-01-27 13:23:55,New Asian Market - Omaha 10 AM,Queen (7),2023-01-27 13:33:55,1,0,928.02,1928.4,7.999533,00:11:54,68107,Omaha,S 26th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-12
853,1009607,13,2023-01-27 13:36:25,Shang Hai Garden - Omaha B4 NOON,Queen (7),2023-01-27 13:46:25,1,0,374,1554.4,0.592788,00:02:30,68108,Omaha,S 24th St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-13
854,1009607,14,2023-01-27 14:01:45,Taste Of China - Council Bluff,Queen (7),2023-01-27 14:11:45,1,0,372,1182.4,7.692575,00:15:20,51503,Council Bluffs,Pearl St,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-14
855,1009607,15,2023-01-27 14:15:19,Great Wall Express - Broadway,Queen (7),2023-01-27 14:25:19,1,0,717.4,465,0.736946,00:03:34,51503,Council Bluffs,E Broadway,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-15
856,1009607,16,2023-01-27 14:35:15,Great Wall Express - Woodburry,Queen (7),2023-01-27 14:45:15,1,0,465,0,2.323928,00:09:56,51503,Council Bluffs,Woodbury Ave,00:10:00,2023-01-27 06:00:00,1489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009607-16
857,1009607,17,2023-01-27 17:37:35,Queen Foods,Queen (7),2023-01-27 17:37:35,0,0,0,0,181.82191,02:52:20,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,1489.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0,1009607-17
860,1009639,0,2023-01-27 06:00:00,Queen Foods,Queen (11),2023-01-27 06:29:59,7,6516.92,0,6516.92,0,00:00:00,66105,Kansas City,S 14th St,00:29:59,2023-01-27 06:00:00,489.0,2023-01-27 19:00:00,00:00:00,0 days 00:29:59,0,29,59,1009639-0
861,1009639,1,2023-01-27 06:50:40,Cosentino's Price Chopper #106,Queen (11),2023-01-27 07:00:40,1,0,1375.7,5141.22,15.383287,00:20:41,64133,Kansas City,E 63rd St,00:10:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009639-1
862,1009639,2,2023-01-27 07:05:47,Ma Ma China - Raytown,Queen (11),2023-01-27 07:15:47,1,0,475.5,4665.72,1.362667,00:05:07,64133,Kansas City,Raytown Rd,00:10:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009639-2
863,1009639,3,2023-01-27 07:33:47,China Town Cafe - Blue Springs,Queen (11),2023-01-27 07:43:47,1,0,1889.56,2776.16,11.655059,00:18:00,64015,Blue Springs,SW East US Highway 40,00:10:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009639-3
864,1009639,4,2023-01-27 07:50:21,Tokyo Grill - Blue Springs,Queen (11),2023-01-27 08:00:21,1,0,338.67,2437.49,4.197984,00:06:34,64014,Blue Springs,SW US Highway 40,00:10:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009639-4
865,1009639,5,2023-01-27 08:02:17,"LB Pop KS, LLC - Popeyes #12359",Queen (11),2023-01-27 08:12:17,1,0,1036.79,1400.7,0.75683,00:01:56,64014,Blue Springs,NW MO-7,00:10:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009639-5
866,1009639,6,2023-01-27 08:27:59,Thai Kitchen - Independence,Queen (11),2023-01-27 08:47:59,2,0,1400.7,0,12.629369,00:15:42,64055,Independence,E US Highway 40,00:20:00,2023-01-27 06:00:00,489.0,2023-01-27 18:00:00,00:00:00,0 days 00:20:00,0,20,0,1009639-6
867,1009639,7,2023-01-27 09:08:38,Queen Foods,Queen (11),2023-01-27 09:08:38,0,0,0,0,13.850364,00:20:39,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,489.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0,1009639-7
870,1009631,0,2023-01-27 06:00:00,Queen Foods,Queen (14),2023-01-27 06:30:00,3,955.82,0,955.82,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-27 06:00:00,40089702.0,2023-01-27 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009631-0
871,1009631,1,2023-01-27 06:47:20,New China Star *****,Queen (14),2023-01-27 06:57:20,1,0,294.22,661.6,12.090019,00:17:20,64118,Kansas City,NW Englewood Rd,00:10:00,2023-01-27 06:00:00,40089702.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009631-1
872,1009631,2,2023-01-27 07:11:45,Cosentino's Price Chopper #120,Queen (14),2023-01-27 07:21:45,1,0,445.5,216.1,12.070135,00:14:25,64068,Liberty,S State Route 291,00:10:00,2023-01-27 06:00:00,40089702.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009631-2
873,1009631,3,2023-01-27 07:52:49,Cosentino's Market Brookside #144,Queen (14),2023-01-27 08:02:49,1,0,216.1,0,22.194758,00:31:04,64113,Kansas City,W 62nd Ter,00:10:00,2023-01-27 06:00:00,40089702.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009631-3
874,1009631,4,2023-01-27 08:27:45,Queen Foods,Queen (14),2023-01-27 08:27:45,0,0,0,0,8.724673,00:24:56,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,40089702.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0,1009631-4
877,1009614,0,2023-01-27 06:00:00,Queen Foods,Queen (5),2023-01-27 06:30:00,10,12787.47,0,12787.47,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-27 06:00:00,1789.0,2023-01-27 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009614-0
878,1009614,1,2023-01-27 09:34:26,Cool Basil - Clive 10:00 - 2:30 PM,Queen (5),2023-01-27 09:44:26,1,0,2683.78,10103.69,191.962688,03:04:26,50325,Clive,NW 86th St,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-1
879,1009614,2,2023-01-27 09:56:34,THAI FLAVORS - INGERSOLL ****,Queen (5),2023-01-27 10:06:34,1,0,604.5,9499.19,6.423735,00:12:08,50312,Des Moines,Ingersoll Ave,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-2
880,1009614,3,2023-01-27 10:17:06,Tacos La Familia - Des Moines 9 AM,Queen (5),2023-01-27 10:27:06,1,0,994.59,8504.6,2.612244,00:10:32,50314,Des Moines,6th Ave,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-3
881,1009614,4,2023-01-27 10:31:59,Double Dragon Food Market 9am,Queen (5),2023-01-27 10:41:59,1,0,2214.78,6289.82,1.125303,00:04:53,50314,Des Moines,2nd Ave,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-4
882,1009614,5,2023-01-27 10:55:52,Lucky Bamboo -Ankeny Do NOT Drop!!,Queen (5),2023-01-27 11:05:52,1,0,2788.53,3501.29,10.46824,00:13:53,50021,Ankeny,SE Delaware Ave,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-5
883,1009614,6,2023-01-27 11:13:57,Siam Table - Ankeney **** 71,Queen (5),2023-01-27 11:23:57,1,0,616.4,2884.89,2.586768,00:08:05,50023,Ankeny,N Ankeny Blvd,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-6
884,1009614,7,2023-01-27 11:33:23,SILK ELEPHANT - ANKENY *****,Queen (5),2023-01-27 11:48:23,1,0,1093.6,1791.29,4.081166,00:09:26,50023,Ankeny,SW White Birch Dr,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:15:00,0,15,0,1009614-7
885,1009614,8,2023-01-27 12:02:04,Taki Japanese - Urbandale *****,Queen (5),2023-01-27 12:12:04,1,0,546.64,1244.65,10.831121,00:13:41,50322,Urbandale,NW 86th St,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-8
886,1009614,9,2023-01-27 12:23:06,Phoenix Asian - Clive,Queen (5),2023-01-27 12:53:06,1,0,696.15,548.5,8.228197,00:11:02,50325,Clive,Hickman Rd,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:30:00,0,30,0,1009614-9
887,1009614,10,2023-01-27 13:02:10,Banana Leaf Asian Bistro,Queen (5),2023-01-27 13:12:10,1,0,548.5,0,7.065612,00:09:04,50266,West Des Moines,Mills Civic Pkwy,00:10:00,2023-01-27 06:00:00,1789.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009614-10
888,1009614,11,2023-01-27 16:11:56,Queen Foods,Queen (5),2023-01-27 16:11:56,0,0,0,0,188.296598,02:59:46,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,1789.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0,1009614-11
891,1009659,0,2023-01-27 09:08:38,Queen Foods,Queen (11),2023-01-27 09:38:37,7,7040.6,0,7040.6,0,00:00:00,66105,Kansas City,S 14th St,00:29:59,2023-01-27 06:00:00,689.0,2023-01-27 19:00:00,00:00:00,0 days 00:29:59,0,29,59,1009659-0
892,1009659,1,2023-01-27 09:47:34,Delicias De Honduras 10am,Queen (11),2023-01-27 09:57:34,1,0,459,6581.6,3.630672,00:08:57,66101,Kansas City,N 7th St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-1
893,1009659,2,2023-01-27 10:10:34,Carniceria Y Tortilleria DonAntonio,Queen (11),2023-01-27 10:20:34,1,0,1722.7,4858.9,8.814772,00:13:00,66112,Kansas City,State Ave,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-2
894,1009659,3,2023-01-27 10:22:31,Zoland Asian Market 9:30 AM,Queen (11),2023-01-27 10:32:31,1,0,300,4558.9,0.789141,00:01:57,66112,Kansas City,State Ave,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-3
895,1009659,4,2023-01-27 11:11:26,"LB Pop KS, LLC - Popeyes #12179",Queen (11),2023-01-27 11:21:26,1,0,832.2,3726.7,33.300525,00:38:55,66046,Lawrence,Iowa St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-4
896,1009659,5,2023-01-27 11:56:40,Red Fortune - Bonner Spring 9:00 am,Queen (11),2023-01-27 12:06:40,1,0,360,3366.7,28.474956,00:35:14,66012,Bonner Springs,Oak St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-5
897,1009659,6,2023-01-27 12:27:00,Tacos El Sobrino (Park On Street),Queen (11),2023-01-27 12:37:00,1,0,288.35,3078.35,16.345791,00:20:20,66102,Kansas City,State Ave,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-6
898,1009659,7,2023-01-27 12:45:19,China Town Buffet - 18th,Queen (11),2023-01-27 12:55:19,1,0,3078.35,0,1.723062,00:08:19,66102,Kansas City,S 18th St,00:10:00,2023-01-27 06:00:00,689.0,2023-01-27 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009659-7
899,1009659,8,2023-01-27 13:00:45,Queen Foods,Queen (11),2023-01-27 13:00:45,0,0,0,0,1.716849,00:05:26,66105,Kansas City,S 14th St,00:00:00,2023-01-27 06:00:00,689.0,2023-01-27 19:00:00,00:00:00,0 days 00:00:00,0,0,0,1009659-8

In [3852]:
# Assuming df is your DataFrame
df['ZIP'] = df['ZIP'].astype(str)

In [3853]:
result = df[df['ZIP'].str.contains('72\*\*\*', regex=True)]
print(result)
count = (df['ZIP'] == '72***').sum()
print(count)

Empty DataFrame
Columns: [ID 2, Stop #, Arrival, Site name, Motor vehicle ID, Departure, # Orders, Pickup weight, Delivery weight, Current weight, Distance from release point, Driving time, ZIP, City, Road, Handling time, Start of time slot, PTrip, End of time slot, Delay, Time_Difference, Duration_Hours, Duration_Minutes, Duration_Seconds, unique_identifier]
Index: []
0

In [3854]:
df['ZIP'] = df['ZIP'].replace('72\*\*\*', '72203', regex=True)

# Create dictionary lookup to pull ZIP into df2

In [3855]:
zip_mapping = df.set_index('Road')['ZIP'].to_dict()

In [3856]:
df2['ZIP'] = df2['Unique_Road'].map(zip_mapping)

In [3857]:
zip_mapping2 = df.set_index('Road')['City'].to_dict()

In [3858]:
df2['City'] = df2['Unique_Road'].map(zip_mapping2)

In [3859]:
df2.head()

    Unique_Road    ZIP         City
0     S 14th St  66105  Kansas City
1  S Maguire St  64093  Warrensburg
2  N Maguire St  64093  Warrensburg
3   E Culton St  64093  Warrensburg
4   E Young Ave  64093  Warrensburg

In [3860]:
def extract_zip(row):
    if "*" in row['ZIP']:
        try:
            # Geocode the city to get latitude and longitude
            location = nom.geocode(row['City'])
            if location:
                # Reverse geocode to get the address and extract the zip code
                reverse_location = nom.reverse((location.latitude, location.longitude))
                zip_code = None
                for component in reverse_location.raw.get("address", []):
                    if component.get("postcode"):
                        zip_code = component.get("postcode")
                        break
                if zip_code:
                    return zip_code
            return None
        except Exception as e:
            print(f"Error: {e}")
            return None
    else:
        return row['ZIP']

df2['ZIP'] = df2.apply(extract_zip, axis=1)

In [3861]:
df2.head()

    Unique_Road    ZIP         City
0     S 14th St  66105  Kansas City
1  S Maguire St  64093  Warrensburg
2  N Maguire St  64093  Warrensburg
3   E Culton St  64093  Warrensburg
4   E Young Ave  64093  Warrensburg

In [3862]:
contains_star = df2['ZIP'].fillna('').astype(str).str.contains(r'\*', regex=True)

# Print the rows where "*" is present in 'ZIP'
print(df2[contains_star])

Empty DataFrame
Columns: [Unique_Road, ZIP, City]
Index: []

In [3863]:
df2.shape

(332, 3)

In [3864]:
df2.shape

(332, 3)

In [3865]:
df2.tail(50)

           Unique_Road    ZIP            City
282    S Commercial St  64701   Harrisonville
283       SE Blue Pkwy  64063    Lee's Summit
284          E 23rd St  66046        Lawrence
285          W 23rd St  66046        Lawrence
286         SE 6th Ave  66607          Topeka
287    Fort Riley Blvd  66502       Manhattan
288         Laramie St  66502       Manhattan
289            Moro St  66502       Manhattan
290      Stagg Hill Rd  66502       Manhattan
291    N Washington St  66441   Junction City
292      E Chestnut St  66441   Junction City
293         SW 22nd Pl  66614          Topeka
294       SW Gage Blvd  66604          Topeka
295        Indiana Ave  64130     Kansas City
296         NW 64th St  64151     Kansas City
297              64054  64054     Sugar Creek
298              64014  64014    Blue Springs
299           N 5th St  66048     Leavenworth
300           Front St  66086      Tonganoxie
301      N Woodlawn St  67220         Wichita
302     S Broadway Ave  67211         Wichita
303        S Seneca St  67213         Wichita
304          31st St W  67217         Wichita
305         E Harry St  67207         Wichita
306          S Rock Rd  67207         Wichita
307      W Central Ave  67042       El Dorado
308      Industrial Rd  66801         Emporia
309         Holcomb St  72764      Springdale
310  S Old Missouri Rd  72764      Springdale
311     E Robinson Ave  72764      Springdale
312       W Sunset Ave  72764      Springdale
313      N Thompson St  72764      Springdale
314           S 8th St  72756          Rogers
315        W Walnut St  72756          Rogers
316     SE Walton Blvd  72712     Bentonville
317        W Hudson Rd  72756          Rogers
318           Slack St  72751       Pea Ridge
319  Old Jungermann Rd  63376       St Peters
320        Delmar Blvd  63130        St Louis
321      S Harrison St  66061          Olathe
322         N Pearl St  66071           Paola
323        NW 128th St  50325           Clive
324       Bel Ray Blvd  64012          Belton
325     2010 N 291 Hwy  69701   Harrisonville
326  NE Todd George Rd  64086    Lee's Summit
327          S 36th St  68123        Bellevue
328         S 157th St  68130           Omaha
329          S 26th St  68107           Omaha
330            2nd Ave  50314      Des Moines
331             Oak St  66012  Bonner Springs

# Get ZIP from city name if ZIP is Incorrect

In [3866]:
def get_state_from_zip(zip):
    # Create a Nominatim geolocator
    
    try:
        # Geocode the address
        location = nom.geocode(zip)
        
        # Check if a location was found
        if location:
            # Split the address by commas and extract the state information
            result_list = location.address.split(", ")
            state = result_list[-1]  # Assuming the state is the second-to-last element
            
            # Remove leading and trailing whitespace
            state = state.strip()
            
            return state
        else:
            return "Location not found"
    except Exception as e:
        return str(e)

# Create functions to pull in City, State, Lat, & Long

In [3867]:
def get_city_from_zip(zip):
    # Create a Nominatim geolocator
    
    try:
        # Geocode the address
        location = nom.geocode(zip)
        
        # Check if a location was found
        if location:
            # Split the address by commas and extract the state information
            result_list = location.address.split(", ")
            state = result_list[-2]  # Assuming the state is the second-to-last element
            
            # Remove leading and trailing whitespace
            state = state.strip()
            
            return state
        else:
            return "Location not found"
    except Exception as e:
        return str(e)

In [3868]:
df2['City'] = df2['ZIP'].apply(get_city_from_zip)

In [3869]:
df2.head(50)

              Unique_Road    ZIP               City
0               S 14th St  66105        Kansas City
1            S Maguire St  64093        Warrensburg
2            N Maguire St  64093        Warrensburg
3             E Culton St  64093        Warrensburg
4             E Young Ave  64093        Warrensburg
5           N Burkarth Rd  64093        Warrensburg
6              N State St  66749               Iola
7          Fairground Ave  64037       Higginsville
8               Armour Rd  64116        Kansas City
9         S US Highway 71  64030          Grandview
10            E North Ave  64012             Belton
11           W Foxwood Dr  64083            Raymore
12        N Commercial St  64701      Harrisonville
13             NE Rice Rd  64086        Lees Summit
14             SW Ward Rd  64081        Lees Summit
15             Raytown Rd  64133        Kansas City
16              E 63rd St  64133        Kansas City
17              Wilson Rd  64123        Kansas City
18       Independence Ave  64124        Kansas City
19             Wornall Rd  64114        Kansas City
20          State Line Rd  64114        Kansas City
21             Troost Ave  64131        Kansas City
22              E 51st St  64112        Kansas City
23           Jefferson St  64112        Kansas City
24          Broadway Blvd  64111        Kansas City
25           Prospect Ave  64128        Kansas City
26          Baltimore Ave  64108        Kansas City
27            NE Barry Rd  64155        Kansas City
28                Star Dr  64068            Liberty
29      S State Route 291  64068            Liberty
30       W State Route 92  64060            Kearney
31       N Jesse James Rd  64024  Excelsior Springs
32           Wollard Blvd  64085           Richmond
33          Crown Hill Rd  64024  Excelsior Springs
34              N Ash Ave  64157        Kansas City
35            Campbell St  64106        Kansas City
36              Cherry St  64106        Kansas City
37         N West Park Dr  64116        Kansas City
38             N Oak Trfy  64118        Kansas City
39        NW Englewood Rd  64118        Kansas City
40          NE Antioch Rd  64119        Kansas City
41         N Prospect Ave  64119        Kansas City
42                  64118  64118        Kansas City
43            NW Barry Rd  64153        Kansas City
44            NW 83rd Ter  64152        Kansas City
45  SW East US Highway 40  64015       Blue Springs
46                NW MO-7  64014       Blue Springs
47       SW US Highway 40  64014       Blue Springs
48             S Broadway  64075          Oak Grove
49               S 2nd St  64076             Odessa

In [3870]:
filtered_df = df2[df2['City'] == 'Little Rock']

# Print the filtered DataFrame
print(filtered_df)

Empty DataFrame
Columns: [Unique_Road, ZIP, City]
Index: []

In [3871]:
def get_state_from_zip(zip):
    # Create a Nominatim geolocator
    
    try:
        # Geocode the address
        location = nom.geocode(zip)
        
        # Check if a location was found
        if location:
            # Split the address by commas and extract the state information
            result_list = location.address.split(", ")
            state = result_list[-1]  # Assuming the state is the second-to-last element
            
            # Remove leading and trailing whitespace
            state = state.strip()
            
            return state
        else:
            return "Location not found"
    except Exception as e:
        return str(e)

In [3872]:
df2['State'] = df2['ZIP'].apply(get_state_from_zip)

In [3873]:
df2.tail(50)

           Unique_Road    ZIP            City             State
282    S Commercial St  64701   Harrisonville          Missouri
283       SE Blue Pkwy  64063     Lees Summit          Missouri
284          E 23rd St  66046        Lawrence            Kansas
285          W 23rd St  66046        Lawrence            Kansas
286         SE 6th Ave  66607          Topeka            Kansas
287    Fort Riley Blvd  66502       Manhattan            Kansas
288         Laramie St  66502       Manhattan            Kansas
289            Moro St  66502       Manhattan            Kansas
290      Stagg Hill Rd  66502       Manhattan            Kansas
291    N Washington St  66441   Junction City            Kansas
292      E Chestnut St  66441   Junction City            Kansas
293         SW 22nd Pl  66614          Topeka            Kansas
294       SW Gage Blvd  66604          Topeka            Kansas
295        Indiana Ave  64130     Kansas City          Missouri
296         NW 64th St  64151     Kansas City          Missouri
297              64054  64054    Independence          Missouri
298              64014  64014    Blue Springs          Missouri
299           N 5th St  66048     Leavenworth            Kansas
300           Front St  66086      Tonganoxie            Kansas
301      N Woodlawn St  67220         Wichita            Kansas
302     S Broadway Ave  67211         Wichita            Kansas
303        S Seneca St  67213         Wichita            Kansas
304          31st St W  67217         Wichita            Kansas
305         E Harry St  67207         Wichita            Kansas
306          S Rock Rd  67207         Wichita            Kansas
307      W Central Ave  67042       El Dorado            Kansas
308      Industrial Rd  66801         Emporia            Kansas
309         Holcomb St  72764      Springdale          Arkansas
310  S Old Missouri Rd  72764      Springdale          Arkansas
311     E Robinson Ave  72764      Springdale          Arkansas
312       W Sunset Ave  72764      Springdale          Arkansas
313      N Thompson St  72764      Springdale          Arkansas
314           S 8th St  72756          Rogers          Arkansas
315        W Walnut St  72756          Rogers          Arkansas
316     SE Walton Blvd  72712     Bentonville          Arkansas
317        W Hudson Rd  72756          Rogers          Arkansas
318           Slack St  72751       Pea Ridge          Arkansas
319  Old Jungermann Rd  63376    Saint Peters          Missouri
320        Delmar Blvd  63130     Saint Louis          Missouri
321      S Harrison St  66061          Olathe            Kansas
322         N Pearl St  66071           Paola            Kansas
323        NW 128th St  50325           Clive              Iowa
324       Bel Ray Blvd  64012          Belton          Missouri
325     2010 N 291 Hwy  69701   Viljandi vald  Viljandi Maakond
326  NE Todd George Rd  64086     Lees Summit          Missouri
327          S 36th St  68123        Bellevue          Nebraska
328         S 157th St  68130           Omaha          Nebraska
329          S 26th St  68107           Omaha          Nebraska
330            2nd Ave  50314      Des Moines              Iowa
331             Oak St  66012  Bonner Springs            Kansas

In [3874]:
df2.shape

(332, 4)

In [3875]:
df2['ZIP'] = df2['ZIP'].astype(str)

In [3876]:
# Define a function to create the full address
def create_full_address(row):
    # Check if 'Unique_Roads' is not NaN
    if not pd.isna(row['Unique_Road']) and len(row['Unique_Road']) > 5:
        # Check if a comma already exists in Unique_Roads
        if ',' in row['Unique_Road']:
            # If there's a comma, just concatenate the columns
            full_address = f"{row['Unique_Road']} {row['City']}, {row['State']} {row['ZIP']}"
        else:
            # If no comma exists, add one before concatenating
            full_address = f"{row['Unique_Road']}, {row['City']}, {row['State']} {str(row['ZIP'])}"
    else:
        # Handle cases where 'Unique_Roads' is NaN
        full_address = f"{row['City']}, {row['State']} {str(row['ZIP'])}"
    
    return full_address

# Apply the function to create the full_address column
df2['full_address'] = df2.apply(create_full_address, axis=1)

In [3877]:
df2.tail(50)

,Unique_Road,ZIP,City,State,full_address
282,S Commercial St,64701,Harrisonville,Missouri,"S Commercial St, Harrisonville, Missouri 64701"
283,SE Blue Pkwy,64063,Lees Summit,Missouri,"SE Blue Pkwy, Lees Summit, Missouri 64063"
284,E 23rd St,66046,Lawrence,Kansas,"E 23rd St, Lawrence, Kansas 66046"
285,W 23rd St,66046,Lawrence,Kansas,"W 23rd St, Lawrence, Kansas 66046"
286,SE 6th Ave,66607,Topeka,Kansas,"SE 6th Ave, Topeka, Kansas 66607"
287,Fort Riley Blvd,66502,Manhattan,Kansas,"Fort Riley Blvd, Manhattan, Kansas 66502"
288,Laramie St,66502,Manhattan,Kansas,"Laramie St, Manhattan, Kansas 66502"
289,Moro St,66502,Manhattan,Kansas,"Moro St, Manhattan, Kansas 66502"
290,Stagg Hill Rd,66502,Manhattan,Kansas,"Stagg Hill Rd, Manhattan, Kansas 66502"
291,N Washington St,66441,Junction City,Kansas,"N Washington St, Junction City, Kansas 66441"
292,E Chestnut St,66441,Junction City,Kansas,"E Chestnut St, Junction City, Kansas 66441"
293,SW 22nd Pl,66614,Topeka,Kansas,"SW 22nd Pl, Topeka, Kansas 66614"
294,SW Gage Blvd,66604,Topeka,Kansas,"SW Gage Blvd, Topeka, Kansas 66604"
295,Indiana Ave,64130,Kansas City,Missouri,"Indiana Ave, Kansas City, Missouri 64130"
296,NW 64th St,64151,Kansas City,Missouri,"NW 64th St, Kansas City, Missouri 64151"
297,64054,64054,Independence,Missouri,"Independence, Missouri 64054"
298,64014,64014,Blue Springs,Missouri,"Blue Springs, Missouri 64014"
299,N 5th St,66048,Leavenworth,Kansas,"N 5th St, Leavenworth, Kansas 66048"
300,Front St,66086,Tonganoxie,Kansas,"Front St, Tonganoxie, Kansas 66086"
301,N Woodlawn St,67220,Wichita,Kansas,"N Woodlawn St, Wichita, Kansas 67220"
302,S Broadway Ave,67211,Wichita,Kansas,"S Broadway Ave, Wichita, Kansas 67211"
303,S Seneca St,67213,Wichita,Kansas,"S Seneca St, Wichita, Kansas 67213"
304,31st St W,67217,Wichita,Kansas,"31st St W, Wichita, Kansas 67217"
305,E Harry St,67207,Wichita,Kansas,"E Harry St, Wichita, Kansas 67207"
306,S Rock Rd,67207,Wichita,Kansas,"S Rock Rd, Wichita, Kansas 67207"
307,W Central Ave,67042,El Dorado,Kansas,"W Central Ave, El Dorado, Kansas 67042"
308,Industrial Rd,66801,Emporia,Kansas,"Industrial Rd, Emporia, Kansas 66801"
309,Holcomb St,72764,Springdale,Arkansas,"Holcomb St, Springdale, Arkansas 72764"
310,S Old Missouri Rd,72764,Springdale,Arkansas,"S Old Missouri Rd, Springdale, Arkansas 72764"
311,E Robinson Ave,72764,Springdale,Arkansas,"E Robinson Ave, Springdale, Arkansas 72764"
312,W Sunset Ave,72764,Springdale,Arkansas,"W Sunset Ave, Springdale, Arkansas 72764"
313,N Thompson St,72764,Springdale,Arkansas,"N Thompson St, Springdale, Arkansas 72764"
314,S 8th St,72756,Rogers,Arkansas,"S 8th St, Rogers, Arkansas 72756"
315,W Walnut St,72756,Rogers,Arkansas,"W Walnut St, Rogers, Arkansas 72756"
316,SE Walton Blvd,72712,Bentonville,Arkansas,"SE Walton Blvd, Bentonville, Arkansas 72712"
317,W Hudson Rd,72756,Rogers,Arkansas,"W Hudson Rd, Rogers, Arkansas 72756"
318,Slack St,72751,Pea Ridge,Arkansas,"Slack St, Pea Ridge, Arkansas 72751"
319,Old Jungermann Rd,63376,Saint Peters,Missouri,"Old Jungermann Rd, Saint Peters, Missouri 63376"
320,Delmar Blvd,63130,Saint Louis,Missouri,"Delmar Blvd, Saint Louis, Missouri 63130"
321,S Harrison St,66061,Olathe,Kansas,"S Harrison St, Olathe, Kansas 66061"
322,N Pearl St,66071,Paola,Kansas,"N Pearl St, Paola, Kansas 66071"
323,NW 128th St,50325,Clive,Iowa,"NW 128th St, Clive, Iowa 50325"
324,Bel Ray Blvd,64012,Belton,Missouri,"Bel Ray Blvd, Belton, Missouri 64012"
325,2010 N 291 Hwy,69701,Viljandi vald,Viljandi Maakond,"2010 N 291 Hwy, Viljandi vald, Viljandi Maakon..."
326,NE Todd George Rd,64086,Lees Summit,Missouri,"NE Todd George Rd, Lees Summit, Missouri 64086"
327,S 36th St,68123,Bellevue,Nebraska,"S 36th St, Bellevue, Nebraska 68123"
328,S 157th St,68130,Omaha,Nebraska,"S 157th St, Omaha, Nebraska 68130"
329,S 26th St,68107,Omaha,Nebraska,"S 26th St, Omaha, Nebraska 68107"
330,2nd Ave,50314,Des Moines,Iowa,"2nd Ave, Des Moines, Iowa 50314"
331,Oak St,66012,Bonner Springs,Kansas,"Oak St, Bonner Springs, Kansas 66012"

In [3878]:
df2

,Unique_Road,ZIP,City,State,full_address
0,S 14th St,66105,Kansas City,Kansas,"S 14th St, Kansas City, Kansas 66105"
1,S Maguire St,64093,Warrensburg,Missouri,"S Maguire St, Warrensburg, Missouri 64093"
2,N Maguire St,64093,Warrensburg,Missouri,"N Maguire St, Warrensburg, Missouri 64093"
3,E Culton St,64093,Warrensburg,Missouri,"E Culton St, Warrensburg, Missouri 64093"
4,E Young Ave,64093,Warrensburg,Missouri,"E Young Ave, Warrensburg, Missouri 64093"
...,...,...,...,...,...
327,S 36th St,68123,Bellevue,Nebraska,"S 36th St, Bellevue, Nebraska 68123"
328,S 157th St,68130,Omaha,Nebraska,"S 157th St, Omaha, Nebraska 68130"
329,S 26th St,68107,Omaha,Nebraska,"S 26th St, Omaha, Nebraska 68107"
330,2nd Ave,50314,Des Moines,Iowa,"2nd Ave, Des Moines, Iowa 50314"
331,Oak St,66012,Bonner Springs,Kansas,"Oak St, Bonner Springs, Kansas 66012"

In [3879]:
max_length_index = df2['full_address'].str.len().idxmax()  # Get the index of the maximum length
address_with_max_length = df2.loc[max_length_index, 'full_address']  # Get the value at that index
print(address_with_max_length)

2010 N 291 Hwy, Viljandi vald, Viljandi Maakond 69701

In [3880]:
def get_lat_long(address):
    location = nom.geocode(address)[1]
    
    return location

In [3881]:
df2['Lat & Long'] = df2['full_address'].apply(get_lat_long)

In [3882]:
df2['Lat & Long'] = df2['Lat & Long'].astype(str)
df2['Lat & Long'] = df2['Lat & Long'].str.replace('(', '').str.replace(')', '')
df2[['Lat', 'Long']] = df2['Lat & Long'].str.split(', ', expand=True)
df2.drop('Lat & Long', axis=1, inplace=True)

C:\Users\mbiringanine\AppData\Local\Temp\ipykernel_17492\427964843.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2['Lat & Long'] = df2['Lat & Long'].str.replace('(', '').str.replace(')', '')

In [3883]:
df2.head()

,Unique_Road,ZIP,City,State,full_address,Lat,Long
0,S 14th St,66105,Kansas City,Kansas,"S 14th St, Kansas City, Kansas 66105",39.085350391162,-94.644547189005
1,S Maguire St,64093,Warrensburg,Missouri,"S Maguire St, Warrensburg, Missouri 64093",38.752342983185,-93.736149982426
2,N Maguire St,64093,Warrensburg,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635
3,E Culton St,64093,Warrensburg,Missouri,"E Culton St, Warrensburg, Missouri 64093",38.763712459174,-93.736594458804
4,E Young Ave,64093,Warrensburg,Missouri,"E Young Ave, Warrensburg, Missouri 64093",38.770915782954,-93.733362122243

In [3884]:
df2.drop_duplicates(subset='Unique_Road', inplace=True)

In [3885]:
df2.shape

C:\Users\mbiringanine\Anaconda3\lib\site-packages\IPython\core\displayhook.py:275: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

(332, 7)

# Loop through lookup dict to pull back in to main df

In [3886]:
column_mapping = df2.set_index('Unique_Road')[['ZIP', 'State', 'City', 'full_address', 'Lat', 'Long']].to_dict(orient='index')

In [3887]:
for col in ['ZIP', 'State', 'City', 'full_address', 'Lat', 'Long']:
    df[col] = df['Road'].map(lambda x: column_mapping.get(x, {}).get(col))

In [3888]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds,unique_identifier,State,full_address,Lat,Long
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009616-0,Kansas,"S 14th St, Kansas City, Kansas 66105",39.085350391162,-94.644547189005
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-1,Missouri,"S Maguire St, Warrensburg, Missouri 64093",38.752342983185,-93.736149982426
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-2,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-3,Missouri,"E Culton St, Warrensburg, Missouri 64093",38.763712459174,-93.736594458804
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-4,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635

In [3889]:
df.shape

(764, 29)

In [3890]:
df['Scenario'] = "Week 3 Pre-Com"

In [3891]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds,unique_identifier,State,full_address,Lat,Long,Scenario
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009616-0,Kansas,"S 14th St, Kansas City, Kansas 66105",39.085350391162,-94.644547189005,Week 3 Pre-Com
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-1,Missouri,"S Maguire St, Warrensburg, Missouri 64093",38.752342983185,-93.736149982426,Week 3 Pre-Com
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-2,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635,Week 3 Pre-Com
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-3,Missouri,"E Culton St, Warrensburg, Missouri 64093",38.763712459174,-93.736594458804,Week 3 Pre-Com
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-4,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635,Week 3 Pre-Com

In [3892]:
df['ZIP'].dropna()

2      66105
3      64093
4      64093
5      64093
6      64093
       ...
895    66046
896    66012
897    66102
898    66102
899    66105
Name: ZIP, Length: 764, dtype: object

In [3893]:
df['ZIP'].dropna()

2      66105
3      64093
4      64093
5      64093
6      64093
       ...
895    66046
896    66012
897    66102
898    66102
899    66105
Name: ZIP, Length: 764, dtype: object

In [3894]:
row_with_na = df[df['ZIP'].isna()]
print(row_with_na)
df = df.dropna(subset=['ZIP'])

Empty DataFrame
Columns: [ID 2, Stop #, Arrival, Site name, Motor vehicle ID, Departure, # Orders, Pickup weight, Delivery weight, Current weight, Distance from release point, Driving time, ZIP, City, Road, Handling time, Start of time slot, PTrip, End of time slot, Delay, Time_Difference, Duration_Hours, Duration_Minutes, Duration_Seconds, unique_identifier, State, full_address, Lat, Long, Scenario]
Index: []

In [3895]:
df.isna().sum()

ID 2                           0
Stop #                         0
Arrival                        0
Site name                      0
Motor vehicle ID               0
Departure                      0
# Orders                       0
Pickup weight                  0
Delivery weight                0
Current weight                 0
Distance from release point    0
Driving time                   0
ZIP                            0
City                           0
Road                           0
Handling time                  0
Start of time slot             0
PTrip                          0
End of time slot               0
Delay                          0
Time_Difference                0
Duration_Hours                 0
Duration_Minutes               0
Duration_Seconds               0
unique_identifier              0
State                          0
full_address                   0
Lat                            0
Long                           0
Scenario                       0
dtype: int64

In [3896]:
#df = df.drop(columns = ['Restriction violations'])

In [3897]:
df.shape

(764, 30)

In [3898]:
df['Arrival'] = pd.to_datetime(df['Arrival'])
df['Date'] = df['Arrival'].dt.date

In [3899]:
df.head()

,ID 2,Stop #,Arrival,Site name,Motor vehicle ID,Departure,# Orders,Pickup weight,Delivery weight,Current weight,Distance from release point,Driving time,ZIP,City,Road,Handling time,Start of time slot,PTrip,End of time slot,Delay,Time_Difference,Duration_Hours,Duration_Minutes,Duration_Seconds,unique_identifier,State,full_address,Lat,Long,Scenario,Date
2,1009616,0,2023-01-23 06:00:00,Queen Foods,Queen (3),2023-01-23 06:30:00,9,5946.07,0,5946.07,0,00:00:00,66105,Kansas City,S 14th St,00:30:00,2023-01-23 06:00:00,2385.0,2023-01-23 19:00:00,00:00:00,0 days 00:30:00,0,30,0,1009616-0,Kansas,"S 14th St, Kansas City, Kansas 66105",39.085350391162,-94.644547189005,Week 3 Pre-Com,2023-01-23
3,1009616,1,2023-01-23 07:46:44,Hong Kong Express - 10 am,Queen (3),2023-01-23 07:56:44,1,0,554.78,5391.29,69.300286,01:16:44,64093,Warrensburg,S Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-1,Missouri,"S Maguire St, Warrensburg, Missouri 64093",38.752342983185,-93.736149982426,Week 3 Pre-Com,2023-01-23
4,1009616,2,2023-01-23 07:58:58,Ping Hibachi - Warrensburg,Queen (3),2023-01-23 08:08:58,1,0,515.86,4875.43,0.460436,00:02:14,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-2,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635,Week 3 Pre-Com,2023-01-23
5,1009616,3,2023-01-23 08:09:40,Sabai Thai - Warrensburg,Queen (3),2023-01-23 08:19:40,1,0,1347.8,3527.63,0.160935,00:00:42,64093,Warrensburg,E Culton St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-3,Missouri,"E Culton St, Warrensburg, Missouri 64093",38.763712459174,-93.736594458804,Week 3 Pre-Com,2023-01-23
6,1009616,4,2023-01-23 08:21:21,King's Chef - Warrensburg,Queen (3),2023-01-23 08:31:21,1,0,520,3007.63,0.435581,00:01:41,64093,Warrensburg,N Maguire St,00:10:00,2023-01-23 06:00:00,2385.0,2023-01-23 18:00:00,00:00:00,0 days 00:10:00,0,10,0,1009616-4,Missouri,"N Maguire St, Warrensburg, Missouri 64093",38.769373864675,-93.73544901635,Week 3 Pre-Com,2023-01-23

In [3900]:
df['Week'] = week

In [3901]:
# df['Distance from release point'] = df['Duration']

In [3902]:
df.to_excel('C:/Users/mbiringanine/Desktop/routing_formated511.xlsx', index=False)

In [3903]:
import os

file_path = 'C:/Users/mbiringanine/Desktop/routing_formated511.xlsx'

# Check if the file exists before trying to open it
if os.path.exists(file_path):
    os.system(f'start excel "{file_path}"')
else:
    print(f"File '{file_path}' does not exist.")